### ISSUE TITLE
Istio Auth

### ISSUE THREAD

**Issue by carpenterm** [nginmesh/nginmesh#13]
This project sounds really interesting. Is there any plan to support Istio Auth or some other method of having TLS between pods managed by the side cars?

**Comment by pleshakov** [comment]
@carpenterm Istio Auth is supported -- connections between NGINX proxies are secured with TLS. However, for now, an NGINX-client does not validate the identity of an NGINX-server -- it cannot validate the service account presented in the NGINX-server certificate.

**Comment by carpenterm** [comment]
Thanks for the info @pleshakov
