### ISSUE TITLE
Grafana does not show sample application metrics

### ISSUE THREAD

**Issue by sakows** [nginmesh/nginmesh#17]
In Istio Release 0.4.0 and Nginmesh 0.4.0 Grafana does not show sample application metrics.

To Reproduce, run in GCP Kubernetes cluster version 1.8.4 with alpha feature enabled:
1. kubectl apply -f istio-0.4.0/install/kubernetes/istio.yaml
2. kubectl apply -f nginmesh-0.4.0/install/kubernetes/istio-initializer.yaml
3. kubectl apply -f istio-0.4.0/install/kubernetes/addons/prometheus.yaml
4. kubectl apply -f istio-0.4.0/install/kubernetes/addons/grafana.yaml
5. kubectl -n istio-system port-forward $(kubectl -n istio-system get pod -l app=prometheus -o 
jsonpath='{.items[0].metadata.name}') 9090:9090 &
6. kubectl -n istio-system port-forward $(kubectl -n istio-system get pod -l app=grafana -o 
jsonpath='{.items[0].metadata.name}') 3000:3000 &
7. kubectl apply -f istio-0.4.0/samples/bookinfo/kube/bookinfo.yaml
8. Make few requests to sample application: http://GATEWAY_URL/productpage
9. Open Grafana in browser : http://localhost:3000/dashboard/db/istio-dashboard
Result: No any application data in dashboard.

[Mixer_logs.txt](https://github.com/nginmesh/nginmesh/files/1601981/NGINMESH_MIXER_LOGS.txt)
[Prometheus_logs.txt](https://github.com/nginmesh/nginmesh/files/1601992/prometheus_logs.txt)
[Grafana_logs.txt](https://github.com/nginmesh/nginmesh/files/1601988/Grafana_logs.txt)

**Comment by sehz** [comment]
not supporting mixer for now. closing this.
