### ISSUE TITLE
Where can I find the source codes of nginmesh sidecar?

### ISSUE THREAD

**Issue by zhaohuabing** [nginmesh/nginmesh#3]
Hi, 

I'm very interested in this project. After going through this repository, I can't find source codes of "nginmesh/istio-nginx-sidecar:0.16-beta", I guess it should be open source as well?  Could you please give me a pointer?

Thanks,
Huabing

**Comment by sehz** [comment]
Hi Huabing,

We planned to fully open source Istio sidecar implementation as part of  0.2x release

**Comment by zhaohuabing** [comment]
Hi Sehyoc,

Glad to hear that you guys are planing to open source the nginx sidecar implementation. What time can I expect the 0.2 release?

Thanks,
Huabing

**Comment by sehz** [comment]
We planned to release everything by end of the month.   Meantime, some of the repo will be made public before then.

**Comment by sehz** [comment]
Hi Huabing, we release nginmesh for Istio 0.2.12.   Everything is now public. Please try it and give us feedback.

**Comment by zhaohuabing** [comment]
Awesome, Thanks sehyo.

**Comment by zhaohuabing** [comment]
Hi Sehyo,

Is it possible to manually inject the sidecar instead of initializer?

Thanks,
Huabing

**Comment by sehz** [comment]
Hi Huabing,

We no longer support manual sidecar injection since initializer is much better mechanism and we don't have to build separate tool.   Is there reason why you want to use manual method?

**Comment by zhaohuabing** [comment]
I'm just struggling to
enable the initializer features in my kubernetes cluster which has
been installed via rancher. Therefore I
could use initializer to inject sidecar.
